-- NOTA: Este migration ha sido integrado en sql/init.sql
-- Todo el schema de correspondencia + auth + roles está en las líneas 149-368 de sql/init.sql
-- Este archivo se mantiene solo como referencia.
-- Para inicializar la base de datos desde cero, ejecutar: sql/init.sql
